image: osrf/ros:crystal-desktop
  
build:
  stage: build
  script:
  - colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug
  - colcon test --event-handlers console_cohesion+ --return-code-on-test-failure
  artifacts:
    reports:
      junit:
      - build/cm730_bringup/test_results/cm730_bringup/*.xunit.xml
      - build/cm730driver/test_results/cm730driver/*.xunit.xml
      - build/cm730controller/test_results/cm730controller/*.xunit.xml
      - build/mx_joint_controller/test_results/mx_joint_controller/*.xunit.xml
